"""HTML email formatter for Mirror browsing reports."""

from __future__ import annotations

from datetime import date

from jinja2 import Template

from src.common.logger import get_logger

LOGGER = get_logger(__name__)

_REPORT_TEMPLATE = Template("""\
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         max-width: 680px; margin: 0 auto; padding: 20px; color: #292524; }
  h1 { color: #b45309; font-size: 24px; }
  h2 { color: #78716c; font-size: 18px; margin-top: 28px; border-bottom: 1px solid #e7e5e4; padding-bottom: 4px; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; }
  th, td { text-align: left; padding: 6px 10px; border-bottom: 1px solid #e7e5e4; font-size: 14px; }
  th { font-weight: 600; color: #78716c; font-size: 13px; }
  .productive { color: #15803d; }
  .neutral { color: #78716c; }
  .waste { color: #dc2626; }
  .bar { display: inline-block; height: 14px; border-radius: 3px; vertical-align: middle; }
  .bar-productive { background: #86efac; }
  .bar-neutral { background: #e7e5e4; }
  .bar-waste { background: #fca5a5; }
  .idea { margin-bottom: 16px; }
  .idea-title { font-weight: 600; font-size: 15px; }
  .idea-angle { font-size: 14px; color: #57534e; margin: 2px 0; }
  .idea-source { font-size: 12px; color: #a8a29e; }
  .waste-item { margin-bottom: 8px; font-size: 14px; }
  .waste-time { color: #dc2626; font-weight: 600; }
  .stats { font-size: 13px; color: #78716c; margin-bottom: 20px; }
  .footer { margin-top: 40px; font-size: 12px; color: #a8a29e; border-top: 1px solid #e7e5e4; padding-top: 12px; }
</style>
</head>
<body>
<h1>Mirror — Browsing Report</h1>
<p class="stats">{{ today }} &middot; {{ audit.total_entries }} page visits &middot; {{ "%.1f"|format(audit.total_hours) }}h total
{%- if cost %} &middot; API cost: ${{ "%.4f"|format(cost) }}{% endif %}</p>

<h2>Time Audit</h2>
<table>
<tr>
  <th>Category</th><th>Hours</th><th></th>
</tr>
{% for cat in ['productive', 'neutral', 'waste'] %}
{% set hours = audit.time_by_category.get(cat, 0) %}
{% set pct = (hours / audit.total_hours * 100) if audit.total_hours > 0 else 0 %}
<tr>
  <td class="{{ cat }}">{{ cat | capitalize }}</td>
  <td>{{ "%.1f"|format(hours) }}h</td>
  <td><span class="bar bar-{{ cat }}" style="width: {{ (pct * 3)|int }}px;"></span> {{ "%.0f"|format(pct) }}%</td>
</tr>
{% endfor %}
</table>

<h2>Top Domains</h2>
<table>
<tr><th>Domain</th><th>Time</th><th>Category</th></tr>
{% for domain, hours, cat in audit.top_domains[:10] %}
<tr>
  <td>{{ domain }}</td>
  <td>{{ "%.1f"|format(hours) }}h</td>
  <td class="{{ cat }}">{{ cat }}</td>
</tr>
{% endfor %}
</table>

{% if audit.waste_highlights %}
<h2>Time Sinks</h2>
{% for item in audit.waste_highlights[:5] %}
<div class="waste-item">
  <span class="waste-time">{{ item.duration_minutes }}min</span> on
  <strong>{{ item.domain }}</strong>
  {% if item.title %} — {{ item.title[:60] }}{% endif %}
</div>
{% endfor %}
{% endif %}

{% if audit.daily_pattern %}
<h2>Daily Pattern</h2>
<table>
<tr><th>Day</th><th class="productive">Productive</th><th class="waste">Waste</th><th class="neutral">Neutral</th></tr>
{% for day in ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %}
{% set d = audit.daily_pattern.get(day, {}) %}
<tr>
  <td>{{ day[:3] }}</td>
  <td>{{ "%.1f"|format(d.get('productive', 0)) }}h</td>
  <td>{{ "%.1f"|format(d.get('waste', 0)) }}h</td>
  <td>{{ "%.1f"|format(d.get('neutral', 0)) }}h</td>
</tr>
{% endfor %}
</table>
{% endif %}

{% if ideas %}
<h2>Content Ideas</h2>
{% for idea in ideas %}
<div class="idea">
  <div class="idea-title">{{ idea.title }}</div>
  <div class="idea-angle">{{ idea.angle }}</div>
  {% if idea.inspired_by %}<div class="idea-source">Inspired by: {{ idea.inspired_by }}</div>{% endif %}
</div>
{% endfor %}
{% endif %}

<div class="footer">
  Generated by Content Agent &middot; Mirror v0.1
</div>
</body>
</html>
""")


def format_report(
    audit: dict,
    ideas: list[dict] | None = None,
    cost: float | None = None,
) -> str:
    """Render the Mirror browsing report as HTML."""
    return _REPORT_TEMPLATE.render(
        today=date.today().strftime("%B %d, %Y"),
        audit=audit,
        ideas=ideas or [],
        cost=cost,
    )
