"""HTML email formatter for Mirror browsing reports."""

from __future__ import annotations

from datetime import date

from jinja2 import Template

from src.common.logger import get_logger

LOGGER = get_logger(__name__)

_REPORT_TEMPLATE = Template("""\
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         max-width: 680px; margin: 0 auto; padding: 20px; color: #292524; }
  h1 { color: #b45309; font-size: 24px; }
  h2 { color: #78716c; font-size: 18px; margin-top: 28px; border-bottom: 1px solid #e7e5e4; padding-bottom: 4px; }
  .stats { font-size: 13px; color: #78716c; margin-bottom: 20px; }
  .distractions { font-size: 15px; margin: 8px 0 4px 0; }
  .distraction-item { display: inline; margin-right: 16px; }
  .distraction-domain { font-weight: 600; color: #dc2626; }
  .reading-item { margin-bottom: 10px; font-size: 14px; }
  .reading-domain { font-size: 12px; color: #a8a29e; margin-left: 4px; }
  .idea { margin-bottom: 16px; }
  .idea-title { font-weight: 600; font-size: 15px; }
  .idea-angle { font-size: 14px; color: #57534e; margin: 2px 0; }
  .idea-source { font-size: 12px; color: #a8a29e; }
  .footer { margin-top: 40px; font-size: 12px; color: #a8a29e; border-top: 1px solid #e7e5e4; padding-top: 12px; }
</style>
</head>
<body>
<h1>Mirror — Browsing Report</h1>
<p class="stats">{{ today }} &middot; {{ audit.total_entries }} page visits
{%- if cost %} &middot; API cost: ${{ "%.4f"|format(cost) }}{% endif %}</p>

{% if audit.distraction_summary %}
<h2>Distractions</h2>
<div class="distractions">
{% for domain, hours in audit.distraction_summary.items() %}
<span class="distraction-item"><span class="distraction-domain">{{ domain }}</span>: {{ "%.1f"|format(hours) }}h</span>
{% endfor %}
</div>
{% endif %}

{% if reading_list %}
<h2>Reading List</h2>
{% for item in reading_list %}
<div class="reading-item">
  <a href="{{ item.url }}">{{ item.title }}</a><span class="reading-domain">({{ item.domain }})</span>
</div>
{% endfor %}
{% endif %}

{% if ideas %}
<h2>Content Ideas</h2>
{% for idea in ideas %}
<div class="idea">
  <div class="idea-title">{{ idea.title }}</div>
  <div class="idea-angle">{{ idea.angle }}</div>
  {% if idea.inspired_by %}<div class="idea-source">Inspired by: {{ idea.inspired_by }}</div>{% endif %}
</div>
{% endfor %}
{% endif %}

<div class="footer">
  Generated by Content Agent &middot; Mirror v0.1
</div>
</body>
</html>
""")


def format_report(
    audit: dict,
    ideas: list[dict] | None = None,
    cost: float | None = None,
    reading_list: list[dict] | None = None,
) -> str:
    """Render the Mirror browsing report as HTML."""
    return _REPORT_TEMPLATE.render(
        today=date.today().strftime("%B %d, %Y"),
        audit=audit,
        ideas=ideas or [],
        cost=cost,
        reading_list=reading_list or [],
    )
