"""HTML email formatter for Scout digests."""

from __future__ import annotations

from datetime import date

from jinja2 import Template

from src.common.logger import get_logger

LOGGER = get_logger(__name__)

_DIGEST_TEMPLATE = Template("""\
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         max-width: 680px; margin: 0 auto; padding: 20px; color: #292524; }
  h1 { color: #b45309; font-size: 24px; }
  .meta { font-size: 13px; color: #78716c; margin-bottom: 28px; }
  .item { margin-bottom: 28px; }
  .item-title { font-size: 16px; font-weight: 600; }
  .item-title a { color: #292524; text-decoration: none; }
  .item-title a:hover { color: #b45309; }
  .item-source { font-size: 13px; color: #78716c; margin: 4px 0; }
  .item-why { font-size: 14px; line-height: 1.6; color: #44403c; margin-top: 4px; }
  .footer { margin-top: 40px; font-size: 12px; color: #a8a29e; border-top: 1px solid #e7e5e4; padding-top: 12px; }
</style>
</head>
<body>
<h1>Scout — 5 Reads</h1>
<p class="meta">{{ today }}{% if cost %} &middot; API cost: ${{ "%.4f" | format(cost) }}{% endif %}</p>

{% if items %}
{% for item in items %}
<div class="item">
  <div class="item-title"><a href="{{ item.url }}">{{ item.title }}</a></div>
  <div class="item-source">{{ item.source_label }}{% if item.published %} &middot; {{ item.published.strftime('%b %d') }}{% endif %}</div>
  {% if item.why_read %}<div class="item-why">{{ item.why_read }}</div>{% endif %}
</div>
{% endfor %}
{% else %}
<p>No new content found this cycle.</p>
{% endif %}

<div class="footer">
  Generated by Content Agent &middot; Scout
</div>
</body>
</html>
""")


def format_digest(items: list[dict], cost: float | None = None) -> str:
    """Render the Scout digest as an HTML email body."""
    return _DIGEST_TEMPLATE.render(
        today=date.today().strftime("%B %d, %Y"),
        items=items,
        cost=cost,
    )
