"""HTML email formatter for Scout digests."""

from __future__ import annotations

from datetime import date

from jinja2 import Template

from src.common.logger import get_logger

LOGGER = get_logger(__name__)

_DIGEST_TEMPLATE = Template("""\
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         max-width: 680px; margin: 0 auto; padding: 20px; color: #292524; }
  h1 { color: #b45309; font-size: 24px; }
  h2 { color: #78716c; font-size: 18px; margin-top: 28px; border-bottom: 1px solid #e7e5e4; padding-bottom: 4px; }
  .item { margin-bottom: 20px; }
  .item-title { font-size: 16px; font-weight: 600; }
  .item-title a { color: #292524; text-decoration: none; }
  .item-title a:hover { color: #b45309; }
  .item-meta { font-size: 13px; color: #78716c; margin: 4px 0; }
  .item-summary { font-size: 14px; line-height: 1.6; }
  .item-why { font-size: 13px; color: #b45309; font-style: italic; margin-top: 4px; }
  .score { display: inline-block; background: #fef3c7; color: #92400e;
           padding: 1px 8px; border-radius: 10px; font-size: 12px; font-weight: 600; }
  .footer { margin-top: 40px; font-size: 12px; color: #a8a29e; border-top: 1px solid #e7e5e4; padding-top: 12px; }
  .stats { font-size: 13px; color: #78716c; margin-bottom: 20px; }
</style>
</head>
<body>
<h1>Scout Digest</h1>
<p class="stats">{{ today }} &middot; {{ items | length }} relevant item{{ 's' if items | length != 1 }} found
{%- if cost %} &middot; API cost: ${{ "%.4f" | format(cost) }}{% endif %}</p>

{% if top_picks %}
<h2>Top Picks</h2>
{% for item in top_picks %}
<div class="item">
  <div class="item-title">
    <span class="score">{{ item.relevance_score }}/5</span>
    <a href="{{ item.url }}">{{ item.title }}</a>
  </div>
  <div class="item-meta">{{ item.source_label }}{% if item.published %} &middot; {{ item.published.strftime('%b %d') }}{% endif %}</div>
  <div class="item-summary">{{ item.llm_summary }}</div>
  {% if item.why_it_matters %}<div class="item-why">{{ item.why_it_matters }}</div>{% endif %}
</div>
{% endfor %}
{% endif %}

{% if other_items %}
<h2>Also Interesting</h2>
{% for item in other_items %}
<div class="item">
  <div class="item-title">
    <span class="score">{{ item.relevance_score }}/5</span>
    <a href="{{ item.url }}">{{ item.title }}</a>
  </div>
  <div class="item-meta">{{ item.source_label }}</div>
  <div class="item-summary">{{ item.llm_summary }}</div>
</div>
{% endfor %}
{% endif %}

{% if not items %}
<p>No new relevant content found this cycle. Your sources may not have published since the last run.</p>
{% endif %}

<div class="footer">
  Generated by Content Agent &middot; Scout v0.1
</div>
</body>
</html>
""")


def format_digest(items: list[dict], cost: float | None = None) -> str:
    """Render the Scout digest as an HTML email body."""
    top_picks = [i for i in items if i.get("relevance_score", 0) >= 4]
    other_items = [i for i in items if i.get("relevance_score", 0) < 4]

    return _DIGEST_TEMPLATE.render(
        today=date.today().strftime("%B %d, %Y"),
        items=items,
        top_picks=top_picks,
        other_items=other_items,
        cost=cost,
    )
