"""HTML email formatter for the Weekly Brief."""

from __future__ import annotations

from datetime import date

from jinja2 import Template

_TEMPLATE = Template("""\
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         max-width: 680px; margin: 0 auto; padding: 20px; color: #292524; }
  h1 { color: #1c1917; font-size: 22px; margin-bottom: 4px; }
  .dateline { font-size: 13px; color: #78716c; margin-bottom: 32px; }
  h2 { color: #44403c; font-size: 13px; font-weight: 600; text-transform: uppercase;
       letter-spacing: 0.06em; margin-top: 28px; border-bottom: 1px solid #e7e5e4;
       padding-bottom: 4px; }
  p { font-size: 14px; line-height: 1.75; color: #44403c; margin: 8px 0; }
  .honest-call { background: #fef3c7; border-left: 3px solid #d97706;
                 padding: 14px 16px; margin-top: 32px; border-radius: 2px; }
  .honest-call h2 { border-bottom: none; margin-top: 0; }
  .honest-call p { color: #292524; font-style: italic; }
  .footer { margin-top: 40px; font-size: 12px; color: #a8a29e;
            border-top: 1px solid #e7e5e4; padding-top: 12px; }
</style>
</head>
<body>
<h1>Stevens — Weekly Brief</h1>
<p class="dateline">{{ today }}{% if cost %} &middot; API cost: ${{ "%.4f"|format(cost) }}{% endif %}</p>

{% if sections.time_audit %}
<h2>Time Audit</h2>
<p>{{ sections.time_audit }}</p>
{% endif %}

{% if sections.task_accountability %}
<h2>Task Accountability</h2>
<p>{{ sections.task_accountability }}</p>
{% endif %}

{% if sections.consulting_pulse %}
<h2>Consulting Pulse</h2>
<p>{{ sections.consulting_pulse }}</p>
{% endif %}

{% if sections.week_in_the_machine %}
<h2>Week in the Machine</h2>
<p>{{ sections.week_in_the_machine }}</p>
{% endif %}

{% if sections.upgrade_suggestion %}
<h2>One Upgrade</h2>
<p>{{ sections.upgrade_suggestion }}</p>
{% endif %}

{% if sections.honest_call %}
<div class="honest-call">
<h2>The Honest Call</h2>
<p>{{ sections.honest_call }}</p>
</div>
{% endif %}

<div class="footer">Generated by Content Agent &middot; Stevens v0.1</div>
</body>
</html>
""")


def format_brief(sections: dict, cost: float | None = None) -> str:
    """Render the Weekly Brief as HTML."""
    return _TEMPLATE.render(
        today=date.today().strftime("%A, %B %d, %Y"),
        sections=sections,
        cost=cost,
    )
