"""HTML email formatter for Tuner digests."""

from __future__ import annotations

from datetime import date, timedelta
from itertools import groupby

from jinja2 import Template

from src.common.logger import get_logger

LOGGER = get_logger(__name__)

_DIGEST_TEMPLATE = Template("""\
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         max-width: 680px; margin: 0 auto; padding: 20px; color: #292524; }
  h1 { color: #0f766e; font-size: 24px; }
  .meta { font-size: 13px; color: #78716c; margin-bottom: 28px; }
  .show { margin-bottom: 32px; }
  .show-name { font-size: 15px; font-weight: 700; color: #0f766e; margin-bottom: 10px; border-bottom: 1px solid #e7e5e4; padding-bottom: 4px; }
  .episode { margin-bottom: 18px; padding-left: 8px; }
  .episode-title a { font-size: 15px; font-weight: 600; color: #292524; text-decoration: none; }
  .episode-title a:hover { color: #0f766e; }
  .episode-meta { font-size: 12px; color: #78716c; margin: 3px 0; }
  .episode-summary { font-size: 14px; line-height: 1.6; color: #44403c; margin-top: 4px; }
  .footer { margin-top: 40px; font-size: 12px; color: #a8a29e; border-top: 1px solid #e7e5e4; padding-top: 12px; }
</style>
</head>
<body>
<h1>Tuner — Podcast Week</h1>
<p class="meta">{{ date_range }}{% if cost %} &middot; API cost: ${{ "%.4f" | format(cost) }}{% endif %}</p>

{% if grouped %}
{% for show_name, episodes in grouped %}
<div class="show">
  <div class="show-name">{{ show_name }}</div>
  {% for ep in episodes %}
  <div class="episode">
    <div class="episode-title">
      {% if ep.url %}<a href="{{ ep.url }}">{{ ep.title }}</a>{% else %}{{ ep.title }}{% endif %}
    </div>
    <div class="episode-meta">
      {% if ep.published %}{{ ep.published.strftime('%b %d') }}{% endif %}
      {% if ep.duration %} &middot; {{ ep.duration }}{% endif %}
    </div>
    {% if ep.summary_text %}<div class="episode-summary">{{ ep.summary_text }}</div>{% endif %}
  </div>
  {% endfor %}
</div>
{% endfor %}
{% else %}
<p>No new episodes this week.</p>
{% endif %}

<div class="footer">
  Generated by Content Agent &middot; Tuner
</div>
</body>
</html>
""")


def format_digest(episodes: list[dict], cost: float | None = None) -> str:
    """Render the Tuner digest as an HTML email body."""
    today = date.today()
    week_start = today - timedelta(days=6)
    date_range = f"{week_start.strftime('%b %d')}–{today.strftime('%b %d, %Y')}"

    # Group by show, sorted by show name; within each show, sort by published desc
    episodes_sorted = sorted(
        episodes,
        key=lambda e: (e.get("source_label", ""), e.get("published") or date.min),
        reverse=False,
    )
    # Sort episodes within each show by published desc
    grouped = []
    for show_name, group in groupby(episodes_sorted, key=lambda e: e.get("source_label", "Unknown")):
        show_eps = sorted(
            list(group),
            key=lambda e: e.get("published") or date.min,
            reverse=True,
        )
        grouped.append((show_name, show_eps))

    # Sort shows alphabetically
    grouped.sort(key=lambda x: x[0])

    return _DIGEST_TEMPLATE.render(
        date_range=date_range,
        grouped=grouped,
        cost=cost,
    )
